audit_header: false
title: New Jersey Real Estate Video Blog with Brett Sikora
description: >-
  Our mission at The Sikora Group is to be your best resource for New Jersey
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The The Sikora Group, your professional
  New Jersey Real Estate Agents.
show_custom_links: false
custom_links:
  - title: Communities
    url: 'http://www.sellwithsikora.com/local/hoboken'
  - title: Testimonials
    url: 'http://www.zillow.com/profile/Brett-Sikora/reviews'
  - title: About
    url: 'http://www.sellwithsikora.com/about-me/'
client:
  name: Brett Sikora
  title:
  license_number:
  about_markdown: >-
    Real estate is my passion and you'll quickly see why my team separates
    itself from the competition. I started in Morris County in 2007 and moved to
    Hoboken to grow one of the the strongest real estate teams in all of Hudson
    County. While maintaining a strong base in Hoboken and downtown Jersey City,
    I started growing a second team in Morris County.


    Whether you're a 1st time home buyer or a large developer, my team's number
    one priority is making sure we're on the same page as our clients throughout
    the buying and selling process, so we can get through each transaction as
    smoothly and efficiently as possible. I always respond to calls/texts/emails
    immediately and if I'm not available, I'll make sure one of my partners
    responds to address any concern you may have. Give me a call today so we can
    get started!
  market: New Jersey
  brand: The Sikora Group
  brokerage: Powered by eXp
  address: '28 Valley Rd Ste 1<br>Montclair, NJ 07042'
  phone: (973) 590-8205
  phone_type: Mobile
  phone2: (866-201-6210
  phone2_type: Office
  email: clientcare@sellwithsikora.com
  url: 'http://www.sellwithsikora.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://www.sellwithsikora.com/home-valuation/'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.sellwithsikora.com/results-gallery/?photo=1&sort=importdate&status=A%2CCS'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your New Jersey Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'https://www.sellwithsikora.com/home-valuation/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/007.jpg
    CTA_title2: Looking for a New Jersey Home?
    CTA_text2: Search the entire MLS for your New Jersey home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://www.sellwithsikora.com/results-gallery/?photo=1&sort=importdate&status=A%2CCS'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/sellwithsikora/?ref=bookmarks'
  linkedin_url: 'https://www.linkedin.com/in/brettsikora'
  youtube_url: 'https://www.youtube.com/channel/UCHZYBPRhCIRBwkZi-K9MDgA'
  twitter_url: 'https://twitter.com/TheSikoraGroup'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Brett-Sikora'
  trulia_url: >-
    http://www.trulia.com/profile/brett-sikora-agent-hoboken-nj-zgwy3ch4/overview
  yelp_url: >-
    http://www.yelp.com/biz/brett-sikora-keller-williams-city-life-realty-hoboken
  podcast_url: >-
    https://itunes.apple.com/us/podcast/hoboken-real-estate-podcast/id1068541254?mt=2
podcast:
  title: New Jersey Real Estate Podcast with Brett Sikora
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the North
    Jersey Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from The Sikora Group - your professional
    New Jersey Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in New Jersey,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Brett Sikora
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: New Jersey Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#090642'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#ffffff'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
